### ISSUE TITLE
Reorganize repo as a Python library

### ISSUE THREAD

**Issue by akariv** [hasadna/OpenCaptcha#1]
So that it can be installed from pip

**Comment by ronniemaor** [comment]
I'm actually not sure what is required in order to make this pip installable. Can you provide more details and/or an example project?

**Comment by RoySegall** [comment]
If someone need help with this one - I'm here

**Comment by ronniemaor** [comment]
> If someone need help with this one - I'm here

Yep, would love some guidance on how to make this pip installable. A simple reference project would also help a lot.

**Comment by RoySegall** [comment]
Well - You can have a look here - https://packaging.python.org/tutorials/packaging-projects/. Also, this one looks promising - https://github.com/audreyr/cookiecutter-pypackage.

Generally, After setting up the project structure you'll need to work on the package in a dev mode. All you need to do is (in the project's folder of course):
`pip install . -e` 

This will ensure that any changes that you made will reflect to the pip packages (or to your virtualenv). This generally how I'm developing my packages. You can also look on [this](https://github.com/RoySegall/django-tivol) package I created, just so you could any reference and see I set my Travis incase cookie cutter set up something wrong.

**Comment by akariv** [comment]
This is a good template to start with:

https://github.com/okfn/oki-py

**Comment by zivmaor** [comment]
Took a lot of mucking around, trial and error, but seems to be working now + integrated with travis and coveralls. Tox still not working on my local env (pycharm on windows) but not sure it's a blocker.
