### ISSUE TITLE
Deploy to PyPI and integrate future deployments with travis

### ISSUE THREAD

**Issue by zivmaor** [hasadna/OpenCaptcha#14]

**Comment by zivmaor** [comment]
@akariv deployment to PyPI needs an API token, which is associated with a PyPI account. Seems to me like this should be owned by hasadna and not me personally. Do you have an encrypted API token I can use from some other project? If not I think I'll need you to generate one for me so I can plug it in the .travis.yml, like here:
https://github.com/okfn/oki-py/blob/master/.travis.yml#L52

**Comment by akariv** [comment]
Open an account, push to pypi and add me as owner (akariv)

**Comment by ronniemaor** [comment]
Done. Also checked that I can "pip install open-captcha" from a fresh venv.
What now? Do we replace my encrypted token with yours? Once that's done I'll delete my token from PyPI.

**Comment by ronniemaor** [comment]
Never mind. I created another token that's restricted to only this project, updated .travis.yml and deleted the previous token. I was uneasy about having a publicly viewable token that would allow anyone to push to any of my (hypothetical other) projects. Now that's fixed I don't see an issue with keeping this API token.

**Comment by akariv** [comment]
I hope that you've encrypted the token, right?

**Comment by ronniemaor** [comment]
Yes, that's what I needed to install Ruby/Travis on the laptop for.
