### ISSUE TITLE
Connect to CI platform

### ISSUE THREAD

**Issue by akariv** [hasadna/OpenCaptcha#2]
We use travis-ci.org.

 on CI we:
- Run tests
- Run linter
- Deploy to pip on tagged commits

**Comment by ronniemaor** [comment]
Can you provide more details on how to connect to travis-CI. Read access to another project I could use as an example would be very helpful.

**Comment by akariv** [comment]
https://github.com/okfn/oki-py also has travis-ci integration

**Comment by zivmaor** [comment]
Works (no lint yet)
