### ISSUE TITLE
Implement chart drawing in Challenge templates

### ISSUE THREAD

**Issue by akariv** [hasadna/OpenCaptcha#8]

**Comment by zivmaor** [comment]
Looked at a comparison of python data visualization libraries:
https://mode.com/blog/python-data-visualization-libraries/

Will probably go with Bokeh for the simple use and aesthetic charts. We don't need interactivity so will just export to PNG. This choice is an internal implementation detail, so it can be changed later if needed.

**Comment by zivmaor** [comment]
Bokeh needs webdriver to export images to PNG, so we're paying for the interactivity we don't want. Will use matplotlib instead.

**Comment by zivmaor** [comment]
Done
